### PR TITLE
Release 2.0.0 alpha.4

### PR DESCRIPTION
**Pull request by JackMorganNZ**
**Notable changes:**

Adds a new searching algorithms topic including lessons, resources, and curriculum integrations. New lessons for existing topics have also been added.

**Changelog:**

- Add searching algorithms topic. #548
- Add 12 and 13 digit barcode checksum poster resources. #545 #546
- Add searching card resource. #547
- Update treasure hunt resource to include optional instruction sheet and colour version.
- Display alpha version number in header. #559
- Force HTTPS connection. #497
- Convert “Butterfly” and “Red Riding Hood” into sorting cards resource variants. #534 #535
- Update resources to new resource module specification.
- Allow raw HTML as source for resource generation.
- Use UCCSER Docker images for stability. #231
- Improve readability and efficiency of CSU helper script.
- Update Kidbots images to animations.
- Add video for Product Code Check Digits lesson.
- Add Unplugged Programming: Kidbots lesson 1 for ages 5 - 7. #551
- Add Unplugged Programming: Kidbots lesson 2 for ages 5 - 7. #550
- Add Sorting Network lesson 2 for ages 5 - 7. #595
- Add curriculum integrations for searching algorithms. #589
- Update automated deployment infrastructure. #587 #590
- Add hover state for coloured panels. #591
- Fix bug where sorting network cards render incorrectly. #596
- Fix typo in 12-digit product code instructions (thanks @eemshi). #599
- Open PDF resource download in new tab. #431
- Fix bug in Google analytics. #539

### CODE REVIEW

**Comment by JackMorganNZ** [comment]
@tah942 I have noticed the 'Searching Algorithms' unit plan doesn't have the same name as our internal planning document. Will investigate this next week.

**Comment by hayleyavw** [comment]
Binary Checksum Poster generates a blank page before and after the poster, as a result of the image being too large. I tested this with the default settings of 12 digits and A4 sized.

**Comment by hayleyavw** [comment]
why'd we change from ``production`` to ``deployed`` ?

**Comment by JackMorganNZ** [comment]
> @hayleyavw "why'd we change from `production` to `deployed`?"

The function is for checking if the system is in a deployed environment (so production or dev server) compared to just production. I thought it would remove ambiguity with this name change, unless you are happy with the former name.

**Comment by hayleyavw** [comment]
@JackMorganNZ re prov v deployed, totally fine with this decision, was just curious as to what prompted it :)

**Comment by tah942** [comment]
- Home > Resources > Treasure Hunt change the heading "Include instruction sheet" to Include instruction sheets". 

- Home > Resources > Binary search teacher helper sheet. 
Relabel to: Include teacher guide sheet
Change the header in the document to read Teacher guide sheet for binary search activity

On the searching cards resource, add the text fold on the sheets as it looks like I should cut out the squares. 

Searching cards resource, the layout for US Letter cuts off part of the resource card.

**Comment by tah942** [comment]
Error detection and correction > Resources > Add the Barcode Checksum Poster to this unit.

**Comment by tah942** [comment]
Product code check digits lesson 2 - under Preparatory knowledge, can we hyperlink to the Modulo operator lesson being referred to in this description?

**Comment by JackMorganNZ** [comment]
@tah942 Have made changes based on your comments above.

**Comment by tah942** [comment]
Under the Searching algorithms topic, relabel the unit plan to be sequential and binary search (but let me know if that's too long!)

**Comment by JackMorganNZ** [comment]
Travis test failed due to Travis cutting network. Restarted test and it passed successfully.

**Pull request merged**
