### PR TITLE
Add error correction and detection programming challenges (fixes #391)

### LINKED ISSUE #391: Add error correction and detection programming exercises
# Progress

## Lesson 1 (Parity):

- [x] 1.1
- [x] 1.2
- [x] 2.1
- [x] 2.2
- [x] 3.1
- [x] 4.1
- [x] 4.2
- [x] 5.1
- [x] 6.1

## Lesson 2 (Product codes):
- [x] 1.1 (12 digits)
- [x] 1.2
- [x] 1.3
- [x] 1.4
- [x] 1.5
- [x] 1.6
- [x] 2.1 (13 digits)
- [x] 2.2
- [x] 2.3
- [x] 2.4
- [x] 2.5
- [x] 2.6

## Other challenges:
- [x] 1.1
- [x] 1.2
- [x] 2.1
- [x] 2.2

# Issues encountered:

- Parity Challenge 1.1 and 2.2 had the learning outcome:
  > Explain how to use an if statement to perform an action based on a condition.

  but this wasn't available. The following learning outcome has been used instead:

  > Identify when to use an if statement to check a set of conditions.

- For Parity 3.1, 4.1, and 4.2 the following learning outcomes are not available:
  > Explain what the “Mod” operator does in your program.

  > Explain the difference between an if else statement and an if statement and how you have used them in your program.

- Parity 4.2 updated input/output tables to be consistent.

- Parity 5.2 and 6.1 doesn't have the learning outcome:
  > Identify when to use a list to store a set of data.

- Product codes (12 digits) 1.2 the following learning outcome is not available:
  > Explain what the “Mod” operator does in your program.

- Product codes (12 digits) 1.3 and 1.4 the following learning outcomes are not available:
  > Describe how a nested statement works in relation to your program.

- Product codes (12 digits) 1.5 the following learning outcome is not available:
  > Demonstrate how you used a loop to have statements executed the necessary number of times

- Product codes (12 digits) 1.4 and 1.6: Renamed titles to be consistent with others.

- Product codes (13 digits) 1.1 and 1.2 (didn't check from then on) has **different** learning outcomes to 12 digits exercises. I have kept the 12 digit learning outcomes.

- Some output has full stops, and some don't.

- Testing examples were hard to display in some cases, so are displayed in panels.

- Should product code 'any length' be the final exercise?

### PR DESCRIPTION
**Pull request by JackMorganNZ**
# Proposed changes

The following programming challenges were added. Formatting is slightly inconsistent (switched from screenshots to Scratch comments part way through) but this pull request focuses on adding content.

## Lesson 1 (Parity):
- 1.1
- 1.2
- 2.1
- 2.2
- 3.1
- 4.1
- 4.2
- 5.1
- 6.1

## Lesson 2 (Product codes):
- 1.1 (12 digits)
- 1.2
- 1.3
- 1.4
- 1.5
- 1.6
- 2.1 (13 digits)
- 2.2
- 2.3
- 2.4
- 2.5
- 2.6

## Other challenges:
- 1.1
- 1.2
- 2.1
- 2.2

# Issues encountered

These issues either need to be fixed before the pull request is merged, or created into a new issue to solve later.

- [x] Parity Challenge 1.1 and 2.2 had the learning outcome:
  > Explain how to use an if statement to perform an action based on a condition.

  but this wasn't available. The following learning outcome has been used instead:

  > Identify when to use an if statement to check a set of conditions.

- [x] For Parity 3.1, 4.1, and 4.2 the following learning outcomes are not available:
  > Explain what the “Mod” operator does in your program.

  > Explain the difference between an if else statement and an if statement and how you have used them in your program.

- [x] Parity 4.2 updated input/output tables to be consistent.

- [x] Parity 5.2 and 6.1 doesn't have the learning outcome:
  > Identify when to use a list to store a set of data.

- [x] Product codes (12 digits) 1.2 the following learning outcome is not available:
  > Explain what the “Mod” operator does in your program.

- [x] Product codes (12 digits) 1.3 and 1.4 the following learning outcomes are not available:
  > Describe how a nested statement works in relation to your program.

- [x] Product codes (12 digits) 1.5 the following learning outcome is not available:
  > Demonstrate how you used a loop to have statements executed the necessary number of times

- [x] Product codes (12 digits) 1.4 and 1.6: Renamed titles to be consistent with others.

- [x] Product codes (13 digits) 1.1 and 1.2 (didn't check from then on) has **different** learning outcomes to 12 digits exercises. I have kept the 12 digit learning outcomes.

- [x] Some output has full stops, and some don't.

- [x] Testing examples were hard to display in some cases, so are displayed in panels.

- [x] Should product code 'any length' be the final exercise?

### CODE REVIEW

**Comment by tah942** [comment]
All slugs are new Jack, so please check the spreadsheet first.
1.1 and 2.2 replacement learning outcome is fine.
3.1, 4.1, 4.2 add two new learning outcomes to the system using slugs: programming-explain-mod and programming-explain-differences-if-else-if-statements
5.2 and 6.1 programming-identify-list-store-data
Product codes (12 digits) 1.2 use slug: programming-explain-mod
Product codes (12 digits) 1.3 and 1.4 use slug: programming-describe-nested-statement
Product codes (12 digits) 1.5 use slug, which is already in our system: programming-identify-loop
Fine to keep the product code learning outcomes the same.

**Comment by JackMorganNZ** [comment]
Thanks @tah942, I've implemented the fixes, however you stated:

> Product codes (12 digits) 1.5 use slug, which is already in our system: programming-identify-loop

While that slug is in the system, the text doesn't match what was requested on the Google Doc. So I have changed the following:

**Original learning outcome:** `no slug defined` - Demonstrate how you used a loop to have statements executed the necessary number of times.

**New learning outcome:** `programming-identify-loop` - Identify when to use a loop to repeat a set of instructions.

If this is correct, please check my changes and place a new review, otherwise let me know.

**Comment by tah942** [comment]
Jack, the learning outcome has been edited further - Identify how and when to use a loop to repeat a set of instructions.

**Comment by JackMorganNZ** [comment]
I've updated the learning outcome.

**Pull request merged**
