### PR TITLE
Add Sequential and Binary Search lessons for ages 5 to 7 (fixes #807)

### LINKED ISSUE #807: Add Sequential and Binary Search lessons for ages 5 to 7
There are 2 lessons to be added.

### PR DESCRIPTION
**Pull request by JackMorganNZ**
Fixes #807.

#801 makes changes to some images used in this PR, so either this PR or #801 will require small changes depending on which one is merged first.

### CODE REVIEW

**Comment by hayleyavw** [comment]
screen shot 2018-02-02 at 11 54 43 am
This is upsetting....

**Comment by JackMorganNZ** [comment]
It is, but I don't know a better option for the moment. Any suggestions?

**Comment by hayleyavw** [comment]
is there a reason why we can't just change its title?

**Comment by JackMorganNZ** [comment]
Have now put this question to authors.

**Pull request merged**
